(lang dune 3.0)
(using coq 0.3)

(package
  (name test-coq)
  (synopsis "Spectec Wasm formalisation in Coq")
  (depends
    (coq (>= 8.16))
    (coq-mathcomp-ssreflect (and (>= 1.16.0) (<= 1.18.0)))
  )
)
